version: 2.1
orbs:
  go: circleci/go@1.9.0
jobs:
  test:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/install-goreleaser
      - go/goreleaser-release:
          project-path: $CIRCLE_WORKING_DIRECTORY # /home/circleci/project
          publish-release: false
          validate-yaml: true
  publish:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/install-goreleaser
      # TODO fix
      - run:
          name: git tag and push
          command: |
            echo "todo"
      - go/goreleaser-release:
          publish-release: true
          validate-yaml: true
workflows:
  test-and-publish:
    jobs:
      - test
      - publish:
          # TODO fix
          context: NPM ReadWrite
          requires:
            - test
          filters:
            branches:
              only: main