version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/go
  go: circleci/go@1.9.0
  # semver-orb: tv2norge/semver-orb@0.0.1
jobs:
  test:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache:
          key: "test"
      - go/mod-download
      - go/install-goreleaser
      - go/goreleaser-release:
          project-path: /home/circleci/project
          publish-release: false
          validate-yaml: true
      - run:
          command: |
            pwd
            which goreleaser
      - go/save-cache:
          key: "test"

  publish:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache:
          key: "publish"
      - go/mod-download
      - go/install-goreleaser
      - add_ssh_keys:
          fingerprints:
            - "43:ed:58:fc:04:a6:f5:a9:47:c6:31:79:9e:76:e7:f7"
      # - semver-orb/bump
      - run:
          name: git tag and push
          command: |
            # git config --global user.email "`git log --format='%ae' HEAD^!`"
            # git config --global user.name "`git log --format='%an' HEAD^!`"
            # git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf ssh://git@github.com/
            ./scripts/tag.sh
      - go/goreleaser-release:
          project-path: /home/circleci/project
          publish-release: true
          validate-yaml: true
      - go/save-cache:
          key: "publish"
workflows:
  test-and-publish:
    jobs:
      # - test
      # - semver-orb/bump
      - publish:
          context: Goreleaser
          # TODO fix
          # requires:
          #   write:packages
          #   push to main on metronome-homebrew
          # requires:
            # - test
            # - semver-orb/bump
          # filters:
          #   branches:
          #     only: main