version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/go
  go: circleci/go@1.9.0
jobs:
  test:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache:
          key: "test"
      - go/mod-download
      - go/install-goreleaser
      - go/goreleaser-release:
          project-path: /home/circleci/project
          publish-release: false
          validate-yaml: true
      - run:
          command: |
            pwd
            which goreleaser
      - go/save-cache:
          key: "test"

  publish:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache:
          key: "publish"
      - go/mod-download
      - add_ssh_keys:
          fingerprints:
            - "43:ed:58:fc:04:a6:f5:a9:47:c6:31:79:9e:76:e7:f7"
      - run:
          name: git tag and push
          command: |
            git config --global user.email "engineering@metronome.com"
            git config --global user.name "goreleaser"
            ./scripts/tag.sh
      - go/install-goreleaser
      - run:
          name: goreleaser release
          command: |
            goreleaser check
            goreleaser release --clean
      - go/save-cache:
          key: "publish"
workflows:
  test-and-publish:
    jobs:
      - test
      - publish:
          context: Goreleaser
          requires:
            - test
          filters:
            branches:
              only: main